<?php
require_once __DIR__.'/layout/head.phtml';
?>

<?php
require_once __DIR__.'/layout/header.phtml';
?>

	<!-- Begin page content -->
	<main role="main" class="container">
		<h1> <?= $page ["title"] ?> </h1>
		
		<h2 class="mt-5"><a href="<?= $BASE . $f3->alias("repositories") ?>">repositories</a></h2>
	</main>

<?php
require_once __DIR__.'/layout/footer.phtml';
?>

<?php
require_once __DIR__.'/layout/foot.phtml';
?>
