<?php
use olafnorge\borgphp\InfoCommand;

require_once __DIR__.'/layout/head.phtml';
?>

<?php
require_once __DIR__.'/layout/header.phtml';
?>

	<!-- Begin page content -->
	<main role="main" class="container">

		<h1> borg backups </h1>
		<h2> repositories </h2>
		
		<table class="table table-bordered my-3">
			<tr>
				<th>name</th>
				<th>size</th>
			</tr>

<?php
$total_size = 0;
foreach ($data as $name => $repo_infos)
{
	$repo = $conf["repos"][$name];
	?>
	<tr>
		<td><a href="<?= $BASE . $f3->alias("repository", ["repo_name" => $name], []) ?>"><?= $repo["label"] ?></a></td>
		<?php
// 		var_dump($repo_infos); die;
		$size = $repo_infos["cache"]["stats"]["unique_csize"];
		$total_size += $size;
		?>
		<td><?= ByteUnits\Binary::bytes($size)->format("GiB", " ") ?></td>
	</tr>
	<?php
}
?>

				<tr>
					<th>sum</th>
					<th><?= ByteUnits\Binary::bytes($total_size)->format("GiB", " ") ?></th>
				</tr>
				<tr>
					<th>count</th>
					<th><?= count($conf["repos"]) ?></th>
				</tr>
		</table>

	</main>

<?php
require_once __DIR__.'/layout/footer.phtml';
?>

<?php
require_once __DIR__.'/layout/foot.phtml';
?>
