<?php
require_once __DIR__.'/layout/head.phtml';
?>

<?php
require_once __DIR__.'/layout/header.phtml';
?>

	<!-- Begin page content -->
	<main role="main" class="container">

<h1> <?= $repo_label ?> </h1>
<h2> archives </h2>


<script type="text/javascript">
var js_data = <?= json_encode($js_data) ?>
</script>

<div style="height: 250px;">
	<canvas id="archives_chart"></canvas>
</div>

<script src="<?= $BASE . "/node_modules/chart.js/dist/chart.umd.js" ?>"></script>
<script src="<?= $BASE . "/assets/graph.js" ?>"></script>


<table class="table table-bordered my-3">
<tr>
	<th>name</th>
	<th>start</th>
</tr>

<?php
foreach ($archives as $archive)
{
	$dt = new DateTime($archive["start"]);
	$start =  $dt->format("d/m/Y H:i:s");
	?>
	<tr>
		<td><a href="<?= $BASE . $f3->alias("archive", ["repo_name" => $repo_name, "arch_name" => $archive["name"]], []) ?>"><?= $archive["name"] ?></a></td>
		<td><?= $start ?></td>
	</tr>
	<?php
}
?>

<tr>
	<th>count</th>
	<th><?= count($archives) ?></th>
</tr>
</table>

	</main>

<?php
require_once __DIR__.'/layout/footer.phtml';
?>

<?php
require_once __DIR__.'/layout/foot.phtml';
?>

