<?php
require_once __DIR__.'/layout/head.phtml';
?>
 
<?php
require_once __DIR__.'/layout/header.phtml';
?>

	<!-- Begin page content -->
	<main role="main" class="container">

		<h1><?= $conf["hostname_override"] ?? $HOST ?></h1>
		<h2> <?= $repo_label ?> </h2>
		<h3> archives ( <?= count($archives) ?> ) </h3>


<script type="text/javascript">
var js_data = <?= json_encode($js_data) ?>
</script>

<div style="height: 250px;">
	<canvas id="archives_chart"></canvas>
</div>

<script src="<?= $BASE . "/node_modules/chart.js/dist/chart.umd.js" ?>"></script>
<script src="<?= $BASE . "/assets/graph.js" ?>"></script>


<table class="table table-bordered my-3">
	<tr>
		<th>name</th>
		<th>start</th>
		<th>duration</th>
		<th>original size</th>
		<th>compressed size</th>
	</tr>
	
	<?php
	foreach ($archives as $archive)
	{
		$dt = new DateTime($archive["start"]);
		$start =  $dt->format("d/m/Y H:i:s");
		
		$archive_info_value = $archives_info [$archive["name"]];
		if(!empty($archive_info_value))
		{
			$archive_info_value = $archive_info_value ["archives"][0];
			date_default_timezone_set('UTC');
			$duration = date('H:i:s', round($archive_info_value["duration"]));
			?>
			<tr>
				<td><a href="<?= $BASE . $f3->alias("archive", ["repo_name" => $repo_name, "archive_name" => $archive["name"]], []) ?>"><?= $archive["name"] ?></a></td>
				<td><?= $start ?></td>
				<td><?= $duration ?></td>
				<td><?= ByteUnits\Binary::bytes($archive_info_value["stats"]["original_size"])->format("GiB", " ") ?></td>
				<td><?= ByteUnits\Binary::bytes($archive_info_value["stats"]["compressed_size"])->format("GiB", " ") ?></td>
			</tr>
			<?php
		}
		else
		{ // rare case when repo cached info references a non existing archive (could happen when archive cache expires and no backup from a long time)
			?>
			<tr>
				<td><a href="<?= $BASE . $f3->alias("archive", ["repo_name" => $repo_name, "archive_name" => $archive["name"]], []) ?>"><?= $archive["name"] ?></a></td>
				<td><?= $start ?></td>
				<td></td>
				<td></td>
				<td></td>
			</tr>
			<?php
		}
	}
	?>
</table>

	</main>

<?php
require_once __DIR__.'/layout/footer.phtml';
?>

<?php
require_once __DIR__.'/layout/foot.phtml';
?>

