<?php
require_once __DIR__.'/layout/head.phtml';
?>

<?php
require_once __DIR__.'/layout/header.phtml';
?>

	<!-- Begin page content -->
	<main role="main" class="container">

<h1> <?= $repo_name ?> </h1>
<h2> archives </h2>


<script type="text/javascript">
var js_data = <?= json_encode($js_data) ?>
</script>

<div style="height: 250px;">
	<canvas id="archives_chart"></canvas>
</div>

<script src="<?= $BASE . "/node_modules/chart.js/dist/chart.umd.js" ?>"></script>
<script src="<?= $BASE . "/assets/test.js" ?>"></script>


<table>
<tr>
	<th>name</th>
	<th>start</th>
</tr>

<?php
foreach ($archives as $archive)
{
	?>
	<?php
	$dt = new DateTime($archive["start"]);
	$start =  $dt->format("d/m/Y H:i:s");
	?>
	<tr>
		<td><?= $archive["name"] ?></td>
		<td><?= $start ?></td>
	</tr>
	<?php
}
?>

<tr>
	<th>count</th>
	<th><?= count($archives) ?></th>
</tr>
</table>

	</main>

<?php
require_once __DIR__.'/layout/footer.phtml';
?>

<?php
require_once __DIR__.'/layout/foot.phtml';
?>

