<?php

require_once __DIR__.'/layout/head.phtml';
?>

<?php
require_once __DIR__.'/layout/header.phtml';
?>

	<script>
        function autoRefresh() {
            window.location = window.location.href;
        }
        setInterval('autoRefresh()', 10*60*1000); // refresh every 10 minutes
    </script>

	<!-- Begin page content -->
	<main role="main" class="container">

		<h1> <?= $conf["backup_server_name"] ?> </h1>
		<h2> repositories ( <?= count($conf["repos"]) ?> ) </h2>
		
		<table class="table table-bordered my-3">
			<tr>
				<th class="text-center">name</th>
				<th class="text-center">size</th>
				<th class="text-center"># of archives</th>
				<th class="text-center">last archive</th>
			</tr>

<?php
$total_size = 0;
foreach ($data as $name => $row)
{
	$repo = $conf["repos"][$name];
	?>
	<tr>
		<?php
		if(!empty($row["info"]) && !empty($row["list"]))
		{
			$size = $row["info"]["cache"]["stats"]["unique_csize"];
			$total_size += $size;
			
			$dt = new DateTime($row["list"]["archives"][array_key_last($row["list"]["archives"])]["start"]);
			$start =  $dt->format("d/m/Y H:i:s");
			?>
			<td><a href="<?= $BASE . $f3->alias("repository", ["repo_name" => $name], []) ?>"><?= $repo["label"] ?></a></td>
			<td><?= ByteUnits\Binary::bytes($size)->format("GiB", " ") ?></td>
			<td><?= count($row["list"]["archives"]) ?></td>
			<td><?= $start ?></td>
			<?php
		}
		else
		{ // cache return empty value, so even calculation failed. will be fixed on when cache is correctly filled
			?>
			<td><?= $repo["label"] ?></td>
			<td> &nbsp; </td>
			<td> &nbsp; </td>
			<td> &nbsp; </td>
			<?php
		}
		?>
	</tr>
	<?php
}
?>

				<tr>
					<th class="text-end"> TOTAL </th>
					<th><?= ByteUnits\Binary::bytes($total_size)->format("GiB", " ") ?></th>
					<th> &nbsp; </th>
					<th> &nbsp; </th>
				</tr>
		</table>

	</main>

<?php
require_once __DIR__.'/layout/footer.phtml';
?>

<?php
require_once __DIR__.'/layout/foot.phtml';
?>
