<?php
require_once __DIR__.'/layout/head.phtml';
?>

<?php
require_once __DIR__.'/layout/header.phtml';
?>


	<!-- Begin page content -->
	<main role="main" class="container">

<?php
$data =
[
	1,
	12,
	50,
	75,
	90,
];
?>


<div style="height: 200px;">
	<canvas id="myChart"></canvas>
</div>

<script src="<?= $BASE . "/node_modules/chart.js/dist/chart.umd.js" ?>"></script>

<script>
const ctx = document.getElementById('myChart');
  
const data = {
  datasets: [{
    label: 'First Dataset',
    data: [{
      x: 20,
      y: 0,
      r: 10
    }, {
      x: 40,
      y: 0,
      r: 10
    }],
    backgroundColor: 'rgb(255, 99, 132)'
  }]
};

const config = {
  type: 'bubble',
  data: data,
  options: {
    scales: {
      x: {
        type: 'logarithmic',
        position: 'bottom',
      },
      y: {
        display: false,
      }
    },
    maintainAspectRatio: false,
  }
};

new Chart(ctx, config);
</script>

	</main>

<?php
require_once __DIR__.'/layout/footer.phtml';
?>

<?php
require_once __DIR__.'/layout/foot.phtml';
?>

