<?php
require_once __DIR__.'/layout/head.phtml';
?>

<?php
require_once __DIR__.'/layout/header.phtml';
?>


	<!-- Begin page content -->
	<main role="main" class="container">

<?php
// test dataset
$base_timestamp = 1687402800; // 22/06/2023 05:00:00
$js_data =
[
	$base_timestamp-600,		// 10 min
	$base_timestamp-3600,		// 1 h
	$base_timestamp-7200,		// 2 h
	$base_timestamp-86400,		// 1 d
	$base_timestamp-300000,		// more
	$base_timestamp-31536000,	// 1 y
	$base_timestamp-157680000,	// 5 y
];
?>
<script type="text/javascript">
var js_data = <?= json_encode($js_data) ?>
</script>


<div style="height: 250px;">
	<canvas id="archives_chart"></canvas>
</div>

<script src="<?= $BASE . "/node_modules/chart.js/dist/chart.umd.js" ?>"></script>
<script src="<?= $BASE . "/assets/test.js" ?>"></script>

	</main>

<?php
require_once __DIR__.'/layout/footer.phtml';
?>

<?php
require_once __DIR__.'/layout/foot.phtml';
?>

