<?php
require_once __DIR__.'/layout/head.phtml';
?>

<?php
require_once __DIR__.'/layout/header.phtml';
?>


	<!-- Begin page content -->
	<main role="main" class="container">

<?php
$data =
[
	1,
	12,
	50,
	75,
	90,
];
?>


<div style="height: 200px;">
	<canvas id="archives_chart"></canvas>
</div>

<script src="<?= $BASE . "/node_modules/chart.js/dist/chart.umd.js" ?>"></script>
<script src="<?= $BASE . "/assets/test.js" ?>"></script>

	</main>

<?php
require_once __DIR__.'/layout/footer.phtml';
?>

<?php
require_once __DIR__.'/layout/foot.phtml';
?>

