	<footer class="footer">
		<div class="container">
			<span class="text-muted">
				<a class="text-decoration-none" href="https://github.com/"><i class="fa-brands fa-github"></i> github</a> | 
				<a class="text-decoration-none" href="https://github.com/olaulau"><img src="https://avatars.githubusercontent.com/u/1771905" style="max-height: 1rem;" /> olaulau</a> | 
				<a class="text-decoration-none" href="https://github.com/olaulau/backup-ui"><i class="fa-solid fa-hard-drive"></i> backup-ui</a>
			</span>
		</div>
	</footer>
