	<header data-bs-theme="dark">
		<nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
			<div class="container-fluid">
				<a class="navbar-brand" href="<?= $BASE . $f3->alias("homepage") ?>">Borg UI</a>
				<button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse"
					aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
					<span class="navbar-toggler-icon"></span>
				</button>
				
				<div class="collapse navbar-collapse" id="navbarCollapse">
					<ul class="navbar-nav me-auto mb-2 mb-md-0">
						<?php
						foreach($page ["breadcrumbs"] as $i => $breadcrumb) {
							?>
							<li class="nav-item">
								<a class="nav-link disabled" aria-current="page" href="#"> / </a>
							</li>
							<li class="nav-item">
								<a class="nav-link <?= ($i === count($page ["breadcrumbs"])-1) ? "active" : "" ?> <?= ($breadcrumb ["url"] === null) ? "disabled" : "" ?>" aria-current="page" href="<?= $breadcrumb ["url"] ?>"><?= $breadcrumb ["label"] ?></a>
							</li>
							<?php
						}
						?>
					</ul>
					
					<!-- <form class="d-flex" role="search">
						<input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
						<button class="btn btn-outline-success" type="submit">Search</button>
					</form> -->
				</div>
			</div>
		</nav>
	</header>